### ISSUE TITLE
uc123.com导航站源码能否发我一份?

### ISSUE THREAD

**Issue by hacry** [nutteam/nut.components#1]
用了一个多月几乎搜烂了整个网络才找到这里有关于UC123一丁点的介绍。

我不是程序员也不懂代码 只是某天被引导打开了UC123主页就被这风格吸引住了。于是天天百度 GG等收集资料 却完全找不到有关的资料 尝试过仿UC123的模板 但没有想象中的那么容易不像一般的网站 UC123的JS文件全都加了UC的字眼的 最后放弃了 继续大海捞针搜资料  经过一个多月的煎熬 当我精疲力尽的时候终于被我搜到这个页面来了 而且还看见了那熟悉的UC123画面  哎  真不容易啊......

希望作者能把UC123源码发我一份 实在不成发模板发我一下也成。

**Comment by aoto** [comment]
@hacry 这个是公司资产，不能随便给你的哦。
